[package]
name = "smp-resource"
version = "0.1.0"
build = "build.rs"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]

[dependencies]
libc = ""
error-chain = ""
derive_builder = ""

[build-dependencies]
gcc = ""