[package]
name = "starfish"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
license = "MIT/Apache-2.0"
description = """
Async programming with spdk for rust.
"""

[dependencies]
# General
failure = "0.1.1"

# Futures
futures-core = "0.2.1"
futures-util = "0.2.1"
# Define versions of dependencies
#bounded-spsc-queue = "0.2.0"
#crossbeam = "0.3.2"
#error-chain = "0.11.0"
#itertools = "0.7.6"
#libc = "0.2.36"
#mempool = "0.3.1"
#pagecache = "0.2.5"
#slab = "0.4.0"
#slog = "2.1.1"
#slog-async = "2.2.0"
#slog_derive = "0.1.0"
#threadpool = "1.7.1"

rust-spdk = { path = "rust-spdk" }
#starfish-executor = { path = "starfish-executor" }
#starfish-future = { path = "starfish-future" }

[dev-dependencies]
cargo-make = "0.10.0"
hamcrest = "0.1.2"
spectral = "0.6.0"
slog-term = "2.0.2"

[build-dependencies]
bindgen = "0.37.0"
make-cmd = "0.1.0"
toml = "0.4.6"

[workspace]

members = [
  "starfish-executor",
  "starfish-future",
  "rust-spdk",
]
