[package]
name = "smp"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
license = "MIT/Apache-2.0"
description = """
Symmetric multiprocessing for rust.
"""

[dependencies]
smp-core = { path = "smp-core" }
smp-resource = { path = "smp-resource" }

[dev-dependencies]
cargo-make = "0.10.0"

[workspace]
members = [
  "smp-resource",
  "smp-core"
]

# https://sagiegurari.github.io/cargo-make/
