[package]
name = "smp"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
license = "MIT/Apache-2.0"
description = """
Symmetric multiprocessing for rust.
"""

[dependencies]
# Define versions of dependencies
bounded-spsc-queue = "0.2.0"
crossbeam = "0.2.10"
error-chain = "0.5.0"
itertools = "0.5.9"
libc = "0.2.11"
slab = "0.3.0"
slog = "2.1.1"

smp-core = { path = "smp-core" }
smp-resource = { path = "smp-resource" }
smp-file = { path = "smp-file" }
smp-future = { path = "smp-future" }

[dev-dependencies]
cargo-make = "0.10.0"
hamcrest = "0.1.2"
spectral = "0.6.0"
slog-term = "2.0.2"

[workspace]

members = [
  "smp-resource",
  "smp-core",
  "smp-file",
  "smp-future"
]

exclude = [
  "futures-rs"
]
