[package]
name = "tokio-smp"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
license = "MIT/Apache-2.0"
build = "build.rs"
description = """
Symmetric multiprocessing for tokio.
"""

[dependencies]
# Figuring out the memory map
nix = "0.6.0"
libc = "0.2.11"
error-chain = "0.5.0"

# Deriving
custom_derive = "0.1.5"
derive_builder = "0.2.0"

[dev-dependencies]
env_logger = "0.3"

[build-dependencies]
gcc = "0.3.35"

