[package]
name = "starfish-executor"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
description = """
Single threaded executor for futures-rs. No Arc in sight.
"""

edition = '2018'

[dependencies]
futures-preview = ""

[dev-dependencies]
hamcrest2 = "*"
