[package]
name = "starfish-executor"
version = "0.1.0"
workspace = "../"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
description = """
Single threaded executor for futures-rs. No Arc in sight.
"""

[dependencies]
futures-preview = "0.3.0-alpha.1"

[dev-dependencies]
hamcrest = "*"
