version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build spdk
          command: sh .circleci/scripts/build_spdk.sh
      - run:
          name: Install rustup
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - restore_cache:
          keys:
            - deps-${CACHE_VERSION}-{{ .Branch }}-{{ .Revision }}
            - deps-${CACHE_VERSION}-{{ .Branch }}-
            - deps-${CACHE_VERSION}-
      - run:
          name: Cache dependencies
          command: |
            source $HOME/.cargo/env
            cargo fetch
      - save_cache:
          key: deps-${CACHE_VERSION}-{{ .Branch }}-{{ .Revision }}
          paths:
            - "target"
      - run:
          name: Run 'cargo fmt'
          command: |
            source $HOME/.cargo/env
            rustup component add rustfmt-preview
            cargo fmt --all -- --check
      - run:
          name: Run 'cargo clippy'
          command: |
            source $HOME/.cargo/env
            rustup component add clippy-preview
            cargo clippy --all --all-targets --all-features -- -D warnings
      - run:
          name: Run tests
          command: |
            sudo bash .circleci/scripts/run_test.sh 
