version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - spdk-v5-{{ checksum ".circleci/scripts/build_spdk.sh" }}
            - spdk-v5-
      - run:
          name: Build spdk
          command: sh .circleci/scripts/build_spdk.sh
      - save_cache:
          key: spdk-v5-{{ checksum ".circleci/scripts/build_spdk.sh" }}
          paths:
            - "/usr/local"
      - run:
          name: Install rustup
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - restore_cache:
          keys:
            - deps-v1-{{ .Branch }}-{{ .Revision }}
            - deps-v1-{{ .Branch }}-
            - deps-v1-
      - run:
          name: Cache dependencies
          command: |
            source $HOME/.cargo/env
            cargo install cargo-build-deps
            cargo build-deps
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "target"
      - run:
          name: Run 'cargo fmt'
          command: |
            source $HOME/.cargo/env
            rustup component add rustfmt-preview
            cargo fmt --all -- --check
      - run:
          name: Run 'cargo clippy'
          command: |
            source $HOME/.cargo/env
            rustup component add clippy-preview
            cargo clippy --all --all-targets --all-features -- -D warnings
      - run:
          name: Run tests
          command: |
            sudo bash .circleci/scripts/run_test.sh 