version: 2
jobs:
  docker:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build -t $DOCKER_USERNAME/starfish:latest .
      - run: docker push $DOCKER_USERNAME/starfish:latest
  build:
    docker:
      - image: jkozlowski/starfish:latest
        environment:
          DOCKER_BUILDKIT: 1
        # auth:	
        #   username: $DOCKER_USERNAME	
        #   password: $DOCKER_PASSWORD
    steps:
      - restore_cache:
          keys:
            - source-v5-{{ .Branch }}-{{ .Revision }}
            - source-v5-{{ .Branch }}-
            - source-v5-
      - checkout
      - save_cache:
          key: source-v5-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Run 'cargo fmt'
          command: |
            source $HOME/.cargo/env
            rustup component add rustfmt-preview
            cargo fmt --all -- --check
      - run:
          name: Run 'cargo clippy'
          command: |
            source $HOME/.cargo/env
            rustup component add clippy-preview
            cargo clippy --all --all-targets --all-features -- -D warnings
      - run:
          name: Run tests
          command: |
            sudo bash .circleci/scripts/run_test.sh 
workflows:
  version: 2
  build:
    jobs:
      - docker
      - build:
          requires: 
            - docker
