version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - restore_cache:
          keys:
            - source-v4-{{ .Branch }}-{{ .Revision }}
            - source-v4-{{ .Branch }}-
            - source-v4-
      - checkout
      - save_cache:
          key: source-v4-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - spdk-v4-{{ checksum ".circleci/scripts/build_spdk.sh" }}
            - spdk-v4-
      - run:
          name: Build spdk
          command: sh .circleci/scripts/build_spdk.sh
      # - save_cache:
      #     key: spdk-v4-{{ checksum ".circleci/scripts/build_spdk.sh" }}
      #     paths:
      #       - "/usr/local/include"
      #       - "/usr/local/lib"
      # - restore_cache:
      #     keys:
      #       - rust-v4-{{ .Branch }}-{{ .Revision }}
      #       - rust-v4-{{ .Branch }}-
      #       - rust-v4-
      - run:
          name: Install rustup
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
      - run:
          name: Run 'cargo fmt'
          command: |
            rustup component add rustfmt-preview
            cargo fmt --all -- --check
      - run:
          name: Run 'cargo clippy'
          command: |
            rustup component add clippy-preview
            # Enabling warnings trips clippy in generated code that has a compiler warning; 
            # See https://github.com/rust-lang-nursery/rust-clippy/issues/702
            # -- -D warnings
            cargo clippy --all --all-targets --all-features
      - run:
          name: Build starfish
          command: cargo build --all
      - run:
          name: Run tests
          command: |
            dd if=/dev/zero of=/tmp/aiofile bs=2048 count=5000
            sudo /tmp/spdk/scripts/setup.sh
            cargo test --all
      # - save_cache:
      #     key: rust-v4-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - "target/"
      #       - "~/.cargo/"
      #       - "~/.multirust/"