version: 2
jobs:
  docker:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build -t $DOCKER_USERNAME/starfish:latest .
      - run: docker push $DOCKER_USERNAME/starfish:latest
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      # Need to run all these inside docker container

      - restore_cache:
          keys:
            - source-v5-{{ .Branch }}-{{ .Revision }}
            - source-v5-{{ .Branch }}-
            - source-v5-
      - checkout
      - save_cache:
          key: source-v5-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Run 'cargo fmt'
          command: |
            rustup component add rustfmt-preview
            cargo fmt --all -- --check
      - run:
          name: Run 'cargo clippy'
          command: |
            rustup component add clippy-preview
            cargo clippy --all --all-targets --all-features -- -D warnings
      - run:
          name: Run tests
          command: |
            sudo sh .circleci/scripts/run_test.sh 
workflows:
  version: 2
  build:
    jobs:
      - docker
      - build:
          requires: 
            - docker
