version: 2
jobs:
  build:
    docker:
      - image: rust:1.29.0-stretch
    steps:
      - checkout
      - run:
          name: Build spdk
          command: sh ./scripts/build_spdk.sh
      - run:
          name: Greeting
          command: |
            rustup --version
      