[package]
name = "smp-future"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]

[dependencies]
futures-core = { path = "../futures-rs/futures-core" }
futures-util = { path = "../futures-rs/futures-util" }