[package]
name = "starfish-futures"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
description = """
Starfish future utilities
"""

edition = '2018'

[dependencies]
futures-preview = "= 0.3.0-alpha.18"

