[package]
name = "starfish-file"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
description = """
Async File IO
"""

edition = '2018'

[dependencies]
io-uring = ""
liburing-sys = ""

tokio = { git = "https://github.com/tokio-rs/tokio.git", rev="654f9d7", features=["rt-full"] }
tokio-executor = { git = "https://github.com/tokio-rs/tokio.git", rev="654f9d7", features=["current-thread"] }

intrusive-collections = ""
bytes = ""
byteorder = ""
derive_builder = ""
err-derive = ""

[dev-dependencies]
hamcrest2 = "*"
tempfile = ""
