[package]
name = "starfish-file"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
description = """
DMA file subsystem.
"""
edition = '2018'

[dependencies]
spdk-sys = { path = "../spdk-sys" }
failure = ""
futures-preview = "= 0.3.0-alpha.6"

[dev-dependencies]
hamcrest = "*"
