[package]
name = "spdk-sys"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
workspace = "../"
categories = ["external-ffi-bindings"]
build = "build.rs"
description = """
Rust bindings to spdk.
"""

links="spdk"
crate-type = ["staticlib"]

[dependencies]
failure = "*"
failure_derive = "*"

[build-dependencies]
bindgen = "*"
toml = "*"
make-cmd = "*"
