[package]
name = "spdk-sys"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
workspace = "../"
categories = ["external-ffi-bindings"]
build = "build.rs"
description = """
Rust bindings to spdk.
"""

links = "spdk"

[dependencies]
failure = "*"
failure_derive = "*"
futures-preview = "0.3.0-alpha.1"

[build-dependencies]
bindgen = "*"
toml = "*"
make-cmd = "*"
