[package]
name = "smp-spdk"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]
build = "build.rs"

[lib]
name = "smp_spdk"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[dependencies]

[build-dependencies]
bindgen = "*"