[package]
name = "smp-executor"
version = "0.1.0"
authors = ["Jakub Kozlowski <mail@jakub-kozlowski.com>"]

[dependencies]
futures-core = "*"
futures-util = "*"

[dev-dependencies]
futures = "*"
hamcrest = "*"